import { type NextPage } from "next";
import Head from "next/head";
import { useForm, SubmitHandler } from "react-hook-form";

import { api } from "../utils/api";

type Inputs = {
  name: string;
  email: string;
  why: string;
};

const Home: NextPage = () => {
  const newApplicant = api.applicant.createApplicant.useMutation();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const onSubmit:SubmitHandler<Inputs> = (data) => {
    console.log(data);
    newApplicant.mutate(data);
  };

  return (
    <>
      <Head>
        <title>Mayh3m</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center font-sans font-semibold">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <img src="/static/img/logo.png"></img>
          <div className="text-center">
            <p>Congratulations</p>
            <p>Welcome to Mayh<span className="text-red-600">3</span>m Clothing</p>
            <p>By F<span className="text-red-600">3</span>Z</p>
          </div>
          <div className="text-center">

            <h3>Apply today for our first drop and be 1 of 100</h3>

            <form onSubmit={handleSubmit(onSubmit)}>
              <div className="form-control">
                <label>Name</label>
                <input type="text" {...register("name")} />
              </div>
              <div className="form-control">
                <label>Email</label>
                <input type="text" {...register("email")} />
              </div>
              <div className="form-control">
                <label>Why you?</label>
                <textarea {...register("why")} />
              </div>
              <div className="form-control">
                <label></label>
                <button type="submit">Apply</button>
              </div>
            </form>

          </div>
        </div>
      </main>
    </>
  );
};

export default Home;