import Head from "next/head"

const Header = () => {
    return (
        <Head>
        <title>Mayh3m</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>)
    }

export default Header