import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />

      <title>Mayh3m</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/static/favicon.ico" />

      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/static/favicon.ico" />
      <link rel="manifest" href="/manifest.webmanifest" />

    </Head>
  );
};

export default Header;
