import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />

      <title>Mayh3m</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/static/favicon.ico" />

      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/static/favicon.ico" />

      <meta name="theme-color" content={"#fafafa"} />

      {/* <!-- Open Graph / Facebook --> */}
      <meta property="og:locale" content={"en_GB"} />
      <meta property="og:type" content="website" />
      <meta property="og:title" content={"May3hem"} />
      <meta property="og:description" content={"Mayh3em Clothing"} />

      {/* <!-- Twitter --> */}
      <meta
        property="twitter:card"
      />
      <meta property="twitter:title" content={"Mayh3m"} />
      <meta property="twitter:description" content={"Mayh3m Clothing"} />

    </Head>
  );
};

export default Header;
